### ISSUE TITLE
Kitkat support

### ISSUE THREAD

**Issue by BlindWanderer** [gavinhungry/Xposed-NoManualFingerprint#1]
For the Samsung Galaxy S5?

**Comment by gavinhungry** [comment]
Unlikely. I based this off of the fingerprint support in Marshmallow AOSP, so it's doubtful that this will work at all with Samsung's KitKat code (and I don't have a Samsung device to test against).

If your S5 ever gets a Marshmallow update and Samsung doesn't completely bastardize it (except, they will), then this **may** work.
