### ISSUE TITLE
Don't work in Android 6.0.1 MMB29Q

### ISSUE THREAD

**Issue by Raijin56** [gavinhungry/Xposed-NoManualFingerprint#2]
For some reason, the module stopped working for me. I press the fingerprint icon in lockscreen and it don't disable the fingerprint reader to unlock the screen.

I can't tell you when it stopped working because I don't use it frequently. I'm using a Nexus 6P with Android 6.0.1, MMB29Q.

Please, tell me what info or logs you need if it's necessary.

Thank you for your work. I think this module should form part of Android!

**Comment by gavinhungry** [comment]
I'm using a Nexus 6P as well, but I'm on CyanogenMod nightlies. Last I checked, there were no changes in the relevant code between AOSP and CM, but I can look at it again.

**Comment by Raijin56** [comment]
I'll wait then. Thank you! I didn't expect that fast response.

**Comment by Raijin56** [comment]
Hi gavinhungry. 

Do you have some news?

Thank you very much and greetings.

**Comment by gavinhungry** [comment]
Hi @Raijin56,

As far as I can tell, nothing relevant has changed. I'm also on Android 6.0.1 (CyanogenMod 13). I also tested on a [Nexus Factory Image](https://developers.google.com/android/nexus/images), and it worked as expected. I'm closing this, but feel free to keep the discussion going.

**Comment by kvoit** [comment]
I am on a Oneplus 3 (6.0.1, Build-Number ONEPLUS A3003_16_160606). I am not sure if I understand the functionality correctly, but I might have to second this. When I wake the device with the power bottom, I see a finger print symbol on the bottom center. Clicking this just shows "Slide up to unlock". If I slight up to unlock, I get the PIN-Pad, and a finger print symbol above. Clicking that does not do anything. Am I missing something, or is this a bug?

Also, would it be possible to support intents?

**Comment by gavinhungry** [comment]
@kvoit,

When you tap the fingerprint icon (lower center of the lock screen), you should see "Device will stay locked until  you manually lock." This is from Google's Smart Lock implementation (Trusted places, On-body detection, etc.).

You can temporarily disable these unlock mechanisms and require a "manual" unlock entry by tapping the smart lock button (lower center of the lock screen). Normally, doing this still allows for your fingerprint to unlock the device.

All this module does is disallow fingerprint unlock when you've requested the next unlock to be a "manual" unlock.

If you're tapping the fingerprint button on the lock screen and can _still_ unlock with a fingerprint, then you may never have setup Smart Lock. I don't think you actually have to keep any of the Smart Lock options enabled (I don't), but try just turning on a "Trusted place," unlock once automatically while at that location, and then disable the "Trusted place."

**Comment by kvoit** [comment]
For me, this seems to work exclusively when a smartlock mechanism is defined. 
When a trusted location exists, there is a lock at the bottom of the lock screen which also locks fingerprint access. As soon as the trusted location is removed (I don't want one), it becomes a fingerbrint symbol that does not do anything.

**Comment by gavinhungry** [comment]
Hmm. I have no Smart Lock mechanisms enabled. I wonder if this normally works on AOSP, and OnePlus changed something - or maybe it _doesn't_ work on AOSP, and CyanogenMod changed something.
